// <auto-generated />
namespace LibraryManagement.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_dateofbirth_data_type_to_string : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_dateofbirth_data_type_to_string));
        
        string IMigrationMetadata.Id
        {
            get { return "201911201316320_update_dateofbirth_data_type_to_string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
